//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Boat
{
	public virtual object int Cargo
	{
		get;
		set;
	}

	public virtual void Move()
	{
		throw new System.NotImplementedException();
	}
        override public void Accept(Visitor visitor)
        {
            visitor.Visit(this);
        }

}

