using GoudKoorts.Domain;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace GoudKoorts.Domain
{
    public class Boat : PlacableObject
    {
        public Boat(Track track) { this.Track = track; }
        public int _cargo;
        public virtual int Cargo
        {
            get
            {
                return _cargo;
            
            }
            set 
            {
                _cargo = value;
                if (_cargo > 7) 
                { 
                 //   this.Move(); 
                
                }
            }
        }

        public override bool Move()
        {
             if (_cargo < 8) { return true ; }
             if (Track != null)
             {

                 if (Track.Left != null)
                 {
                     return Track.Left.Place(this);
                 }

                 this.Track.content = null;
                 this.Track = null;
             }
            return true;
        }

        override public void Accept(Visitor visitor)
        {
            visitor.Visit(this);
        }

        public override void ChangeFilling()
        {
            this.Cargo++;
        }
    }
}

