//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace GoudKoorts.Domain
{
    public class Cart : PlacableObject
    {

        public Cart(Track Field) { this.Filled = true; this.Track = Field; }
        public virtual bool Filled
        {
            get;
            set;
        }



        public override void Move()
        {
            if (Track.nextTrack != null) {
                Track.nextTrack.Place(this);
            }
        }

        override public void Accept(Visitor visitor)
        {
            visitor.Visit(this);
        }

        public override void ChangeFilling()
        {
            this.Filled = !this.Filled;
        }
    }
}

