//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace GoudKoorts.Domain
{
    public class EmptyTrack : Track
    {
        public EmptyTrack()
        {
            corner = -1;
        }
        public int id
        {
            get;
            set;
        }
        override public void Accept(Visitor visitor)
        {
            visitor.Visit(this);
        }
    }
}

