//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace GoudKoorts.Domain
{
    public class MovableTrack : Track
    {
        public MovableTrack()
        {
            corner = 0;
        }
        public override PlacableObject content
        {
            get;
            set;
        }
        public void move() 
        {
            if (this.content != null) { return; }
            if (this.corner < 3) { this.corner = this.corner + 2; }
            else{this.corner = this.corner - 2;}
        }
        override public void Accept(Visitor visitor)
        {
            visitor.Visit(this);
        }
        public override bool Place(PlacableObject content)
        {
            if (this.previousTrack == null || this.previousTrack.content != content) { return true; }
            if (this.nextTrack == null || this.nextTrack.corner == -1) { return true; }
            if (this.content == null)
            {
                
                this.previousTrack.content = null;
                this.content = content;
                this.content.Track = this;
                return true;
            }
            return false;
        }
    }
}

