using GoudKoorts.Domain;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
namespace GoudKoorts.Domain
{
    public class Track
    {
        public int x;
        public int y;
        public int corner;
        public Track Left
        {
            get;
            set;
        }
        public Track Right
        {
            get;
            set;
        }
        public Track Up
        {
            get;
            set;
        }
        public Track Down
        {
            get;
            set;
        }
        public Track nextTrack
        {
            get;
            set;
        }

        public Track previousTrack
        {
            get;
            set;
        }

        public virtual PlacableObject content
        {
            get;
            set;
        }

        public virtual void visit(Track track)
        {
            throw new System.NotImplementedException();
        }
        public virtual void Accept(Visitor visitor)
        {
            visitor.Visit(this);
        }
        public virtual bool Place(PlacableObject content) 
        {
            if (this.content == null) 
            {
                if (this.previousTrack != null) { this.previousTrack.content = null; }
                this.content = content;
                this.content.Track = this;
                return true;
            }
            return false;
        }
    }
}

