//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Controller
{
	public virtual BoardView BoardView
	{
		get;
		set;
	}

	public virtual Board Board
	{
		get;
		set;
	}

	public virtual void Step()
	{
		throw new System.NotImplementedException();
	}

}

